# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from distributed_task_manager.protos import task_manager_pb2 as distributed__task__manager_dot_protos_dot_task__manager__pb2

GRPC_GENERATED_VERSION = '1.65.4'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.66.0'
SCHEDULED_RELEASE_DATE = 'August 6, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in distributed_task_manager/protos/task_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TaskManagerStub(object):
    """TaskManager service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/TaskManager/CreateTask',
                request_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/TaskManager/GetTask',
                request_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTaskStatus = channel.unary_unary(
                '/TaskManager/UpdateTaskStatus',
                request_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusRequest.SerializeToString,
                response_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusResponse.FromString,
                _registered_method=True)
        self.WatchTask = channel.unary_unary(
                '/TaskManager/WatchTask',
                request_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskRequest.SerializeToString,
                response_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskResponse.FromString,
                _registered_method=True)


class TaskManagerServicer(object):
    """TaskManager service definition
    """

    def CreateTask(self, request, context):
        """RPC for creating a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """RPC for retrieving a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTaskStatus(self, request, context):
        """RPC for updating a task's status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchTask(self, request, context):
        """RPC for watching a task
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskRequest.FromString,
                    response_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskRequest.FromString,
                    response_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskResponse.SerializeToString,
            ),
            'UpdateTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTaskStatus,
                    request_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusRequest.FromString,
                    response_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusResponse.SerializeToString,
            ),
            'WatchTask': grpc.unary_unary_rpc_method_handler(
                    servicer.WatchTask,
                    request_deserializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskRequest.FromString,
                    response_serializer=distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TaskManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('TaskManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskManager(object):
    """TaskManager service definition
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskManager/CreateTask',
            distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskRequest.SerializeToString,
            distributed__task__manager_dot_protos_dot_task__manager__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskManager/GetTask',
            distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskRequest.SerializeToString,
            distributed__task__manager_dot_protos_dot_task__manager__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskManager/UpdateTaskStatus',
            distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusRequest.SerializeToString,
            distributed__task__manager_dot_protos_dot_task__manager__pb2.UpdateTaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TaskManager/WatchTask',
            distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskRequest.SerializeToString,
            distributed__task__manager_dot_protos_dot_task__manager__pb2.WatchTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
